import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Inlined templates for init command
 * These are bundled into the distribution to avoid path resolution issues
 */
const templates: Record<string, string> = {
  "hank.json": `{
  "$schema": "https://unpkg.com/hankweave@latest/schemas/hank.schema.json",
  "meta": {
    "name": "My Workflow",
    "version": "1.0.0",
    "description": "Generated by hankweave init"
  },
  "hank": [
    {
      "id": "analyze-haiku",
      "name": "Analyze Project (Haiku)",
      "model": "haiku",
      "continuationMode": "fresh",
      "promptFile": "./prompts/analyze-haiku.md",
      "checkpointedFiles": ["analysis-haiku.md"],
      "outputFiles": [
        {
          "copy": ["analysis-haiku.md"]
        }
      ]
    },
    {
      "id": "analyze-gemini",
      "name": "Analyze Project (Gemini)",
      "model": "gemini-2.5-flash",
      "continuationMode": "fresh",
      "promptFile": "./prompts/analyze-gemini.md",
      "checkpointedFiles": ["analysis-gemini.md"],
      "outputFiles": [
        {
          "copy": ["analysis-gemini.md"]
        }
      ]
    },
    {
      "id": "analyze-codex",
      "name": "Analyze Project (Codex)",
      "model": "gpt-5.1-codex-mini",
      "continuationMode": "fresh",
      "promptFile": "./prompts/analyze-codex.md",
      "checkpointedFiles": ["analysis-codex.md"],
      "outputFiles": [
        {
          "copy": ["analysis-codex.md"]
        }
      ]
    },
    {
      "id": "analyze-pi",
      "name": "Analyze Project (Pi)",
      "model": "pi/anthropic/claude-haiku-4-5",
      "continuationMode": "fresh",
      "promptFile": "./prompts/analyze-pi.md",
      "checkpointedFiles": ["analysis-pi.md"],
      "outputFiles": [
        {
          "copy": ["analysis-pi.md"]
        }
      ]
    },
    {
      "id": "analyze-opencode",
      "name": "Analyze Project (OpenCode)",
      "model": "opencode/anthropic/claude-haiku-4-5",
      "continuationMode": "fresh",
      "promptFile": "./prompts/analyze-opencode.md",
      "checkpointedFiles": ["analysis-opencode.md"],
      "outputFiles": [
        {
          "copy": ["analysis-opencode.md"]
        }
      ]
    }
  ]
}`,

  "prompts/analyze-haiku.md": `# Project Analysis (Haiku)

Please analyze the files in the \`read_only_data_source\` directory located in the current working directory and create a comprehensive analysis report.

Your analysis should include:

1. Very brief overview of the files in that directory

Please create your analysis in a file called \`analysis-haiku.md\` in the execution directory.`,

  "prompts/analyze-gemini.md": `# Project Analysis (Gemini)

Please analyze the files in the \`read_only_data_source\` directory located in the current working directory and create a comprehensive analysis report.

**Important:** Use bash/shell commands (like \`ls\` and \`cat\`) to list and read files in the \`read_only_data_source\` directory. Do not use the native LS or Read tools for this directory as it may be a symlink.

Your analysis should include:

1. Very brief overview of the files in that directory

Please create your analysis in a file called \`analysis-gemini.md\` in the execution directory.`,

  "prompts/analyze-codex.md": `# Project Analysis (Codex)

Please analyze the files in the \`read_only_data_source\` directory located in the current working directory and create a comprehensive analysis report.

Your analysis should include:

1. Very brief overview of the files in that directory

**Important:** Please create your analysis in a file called \`analysis-codex.md\` in the execution directory using the \`Write\` tool. Do NOT use PowerShell commands (like Set-Content) on Windows.`,

  "prompts/analyze-pi.md": `# Project Analysis (Pi)

Please analyze the files in the \`read_only_data_source\` directory located in the current working directory and create a comprehensive analysis report.

Your analysis should include:

1. Very brief overview of the files in that directory

Please create your analysis in a file called \`analysis-pi.md\` in the execution directory.`,

  "prompts/analyze-opencode.md": `# Project Analysis (OpenCode)

Please analyze the files in the \`read_only_data_source\` directory located in the current working directory and create a comprehensive analysis report.

Your analysis should include:

1. Very brief overview of the files in that directory

Please create your analysis in a file called \`analysis-opencode.md\` in the execution directory.`,

  "README.md": `# Hank

This hank was initialized with \`hankweave init\`.

## Structure

- \`hank.json\` — Workflow definition (codons, models, file tracking)
- \`prompts/\` — Prompt files for each codon (one per harness: Haiku, Gemini, Codex, Pi, OpenCode)
- \`data/\` — Sample data files to analyze
- \`.gitignore\` — Ignore patterns for execution artifacts

## Customization

Edit \`hank.json\` to customize your workflow:
- Add more codons to the \`hank\` array
- Change the \`model\` (haiku, sonnet, opus, gemini-2.5-flash, gpt-5.1-codex-max, etc.)
- Add \`rigSetup\` to prepare your environment before a codon runs
- Configure \`checkpointedFiles\` to track files in git checkpoints
- Use \`overrides\` to suggest runtime settings (model, port, etc.)

## Running

\`\`\`sh
cd <this-directory>
npx hankweave
\`\`\`

## Learn More

- [Docs](https://hankweave.southbridge.ai)
- [Hank Basics](https://hankweave.southbridge.ai/guides/building-a-hank)
- [GitHub](https://github.com/SouthBridgeAI/hankweave-runtime)`,

  ".gitignore": `.hankweave/
*.log
node_modules/`,

  "data/sample1.txt": `# Project Overview

This is a sample project for demonstrating the hankweave workflow system.

## Key Features
- Multi-step AI workflows
- Flexible codon configuration
- File tracking and persistence

## Getting Started
1. Review the hank.json configuration
2. Customize prompts in the prompts/ directory
3. Run your workflow with hankweave`,

  "data/sample2.txt": `# Technical Specifications

## Architecture
- Node.js runtime
- TypeScript for type safety
- Event-driven processing model

## Dependencies
- bun for fast execution
- Anthropic Claude API for AI capabilities

## Configuration
The system uses JSON-based configuration files to define workflows and execution parameters.`,

  "data/notes.txt": `# Development Notes

## TODO
- Add more example workflows
- Improve error handling
- Add unit tests for core functionality

## Ideas
- Support for parallel codon execution
- Integration with other AI providers
- Web-based workflow designer

## Known Issues
- None at this time`,
};

/**
 * Initialize a new hank with basic template files
 */
export async function initProject(targetDir: string): Promise<void> {
  // Ensure target directory exists
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  // Check if directory is empty or only has .git
  const existingFiles = fs.readdirSync(targetDir);

  if (existingFiles.length > 0) {
    throw new Error(
      `Directory ${targetDir} is not empty. Please run init in an empty directory or specify a new directory.`,
    );
  }

  // Create prompts directory
  const promptsDir = path.join(targetDir, "prompts");
  fs.mkdirSync(promptsDir, { recursive: true });

  // Create data directory
  const dataDir = path.join(targetDir, "data");
  fs.mkdirSync(dataDir, { recursive: true });

  // Write template files from inlined content
  for (const [targetPath, content] of Object.entries(templates)) {
    const fullPath = path.join(targetDir, targetPath);
    const dir = path.dirname(fullPath);

    // Ensure parent directory exists
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(fullPath, content, "utf-8");
  }

  console.log(`\n✅ Initialized hank in ${targetDir}\n`);
  console.log("Created files:");
  console.log("  - hank.json");
  console.log("  - prompts/analyze-haiku.md");
  console.log("  - prompts/analyze-gemini.md");
  console.log("  - prompts/analyze-codex.md");
  console.log("  - prompts/analyze-pi.md");
  console.log("  - prompts/analyze-opencode.md");
  console.log("  - data/sample1.txt");
  console.log("  - data/sample2.txt");
  console.log("  - data/notes.txt");
  console.log("  - README.md");
  console.log("  - .gitignore");
}
